version: '3.8'
services:
  service-b-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app  
      - /app/node_modules
    ports:
      - "3002:3002"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - service-b-db
      - otel-collector
    networks:
      - default     

  service-b-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3002:3002"
    environment:
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - service-b-db
    networks:
      - default     
  
  service-b-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: service_b
    ports:
      - "5434:5432"    
    networks:
      - default      

  otel-collector:
      image: otel/opentelemetry-collector-contrib:latest
      volumes:
        - ./otel-collector-config.yml:/etc/otel-collector-config.yml
      command:
        - "--config=/etc/otel-collector-config.yml"
      ports:
        - "4317:4317"  # Porta para OTLP gRPC
        - "4318:4318"  # Porta para OTLP HTTP
      networks:
        - default    

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - '16686:16686'  # Interface do Jaeger
      - '4319:4317'  # Porta de coleta de traços        
    networks:
      - default  

networks:
  default:
    external:
      name: microservices_network
