version: '3.8'
services:
  service-b-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app  
      - /app/node_modules
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=postgres://postgres:password@service-b-db:5432/service_a
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - service-b-db

  service-b-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=postgres://postgres:password@service-b-db:5432/service_a
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - service-b-db
  
  service-b-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: service_b
    ports:
      - "5434:5432"    

networks:
  default:
    external:
      name: microservices_network
