receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"
      grpc:
        endpoint: "0.0.0.0:4317"

exporters:
  otlp/jaeger:
    endpoint: "http://jaeger:4317"
    tls:
      insecure: true

processors:
  batch: {}

extensions:
  health_check:
    check_interval: 60s

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger] # Adicione 'datadog' aqui futuramente

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger] # Adicione 'datadog' aqui futuramente

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger] # Adicione 'datadog' aqui futuramente  
